spring:
  main:
    web-application-type: none
  datasource:
    # H2 (For Spring Batch management tables)
    batch:
      url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
      username: sa
      password:
      driver-class-name: org.h2.Driver

    # MySQL (For business logic)
    business:
      url: jdbc:mysql://mysqlserver:3306/sampledb
      username: sampleuser
      password: samplepassword
      driver-class-name: com.mysql.cj.jdbc.Driver
